spring.application.name=esgo-backend
spring.datasource.url=jdbc:mysql://localhost:3306/esgo_db
spring.datasource.username=root
spring.datasource.password=esgo2025*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Increase upload limit to 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB